apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "cafe-app.fullname" . }}-rollout
  labels:
    app: cafeweb
spec:
  replicas: {{ .Values.replicas.web }}
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600

  selector:
    matchLabels:
      app: cafeweb
      tier: frontend

  template:
    metadata:
      labels:
        app: cafeweb
        tier: frontend
    spec:
      containers:
        - name: cafeweb
          image: "{{ .Values.image.web }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: app-config-volume
              mountPath: /var/www/html/getAppParameters.php
              subPath: getAppParameters.php
      volumes:
        - name: app-config-volume
          configMap:
            name: {{ .Values.configMapName | default "app-config" }}

  # ---- START strategy (must be present) ----
  strategy:
    canary:
      # must include canaryService and stableService
      canaryService: {{ include "cafe-app.fullname" . }}-canary
      stableService:  {{ include "cafe-app.fullname" . }}-stable

      # NGINX traffic routing (Rollouts will update ingress annotations)
      trafficRouting:
        nginx:
          stableIngress: {{ include "cafe-app.fullname" . }}-ingress

      # canary steps
      steps:
        - setWeight: 30
        - pause:
            duration: 60s
        - setWeight: 60
        - pause: {}          # manual promotion step
        - setWeight: 100
  # ---- END strategy ----
