apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "cafe-app.fullname" . }}-rollout
  labels:
    app: cafeweb
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      app: cafeweb
      tier: frontend
  template:
    metadata:
      labels:
        app: cafeweb
        tier: frontend
    spec:
      containers:
        - name: cafeweb
          image: "{{ .Values.image.web }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: app-config-volume
              mountPath: /var/www/html/getAppParameters.php
              subPath: getAppParameters.php
      volumes:
        - name: app-config-volume
          configMap:
            name: {{ .Values.configMapName | default "app-config" }}

  strategy:
  canary:
    canaryService: {{ include "cafe-app.fullname" . }}-canary
    stableService: {{ include "cafe-app.fullname" . }}-stable

    trafficRouting:
      nginx:
        stableIngress: {{ include "cafe-app.fullname" . }}-ingress

    steps:
      - setWeight: 30
      - pause:
          duration: 60s
      - setWeight: 60
      - pause: {}   # manual promotion
      - setWeight: 100
